/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoescare;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Melin
 */
public class Data_Pelanggan extends javax.swing.JFrame {
        Koneksi koneksi;
        Statement st;
        ResultSet rs;
        String gender;
        Map param = new HashMap(); // memebtuk objek param sbg key dan nilai
         
    private void kosongkan_form(){
        nik.setText(null);
        nama.setText(null);
        noHp.setText(null);
        laki.setSelected(false);
        per.setSelected(false);
        alamat.setText(null);
        treatment.setSelectedItem(null);
        jumlah.setText(null);
        tgl_msk.setDate(null);
        tgl_ambil.setDate(null);
        
        
    }
    
    public void tampil(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Gender");
        model.addColumn("No. Hp");
        model.addColumn("Alamat");
        model.addColumn("Treatment");
        model.addColumn("jumlah");
        model.addColumn("tgl_masuk");
        model.addColumn("tgl_ambil");
        
        try{
            int no = 1;
            st =(Statement) koneksi.con.createStatement();
            String sql = "SELECT * FROM data_p";
            rs = st.executeQuery(sql);
            
            while(rs.next()){
                model.addRow(new Object[]{no++,rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)});
                
            }
            tabel_data.setModel(model);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"error : "+e.getMessage());
        }
    }
    /**
     * Creates new form Data_Pelanggan
     */
    public Data_Pelanggan() {
        initComponents();
        setLocationRelativeTo(this);
        koneksi = new Koneksi();
        tampil();
        kosongkan_form();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        noHp = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        treatment = new javax.swing.JComboBox<>();
        tgl_msk = new com.toedter.calendar.JDateChooser();
        tgl_ambil = new com.toedter.calendar.JDateChooser();
        laki = new javax.swing.JRadioButton();
        per = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        nik = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_data = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        jLabel3.setText("NIK");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 52, 23));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        jLabel2.setText("Tgl Masuk");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, 23));

        noHp.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.add(noHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 284, -1));

        nama.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 284, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        jLabel5.setText("Alamat");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 52, 23));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        jLabel6.setText("Treatment");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, 23));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        jLabel7.setText("No. HP");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 52, 23));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        jLabel8.setText("Tgl Ambil");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, 23));

        edit.setBackground(new java.awt.Color(51, 255, 0));
        edit.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, -1, -1));

        add.setBackground(new java.awt.Color(51, 255, 0));
        add.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, -1));

        delete.setBackground(new java.awt.Color(255, 51, 0));
        delete.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, -1, -1));

        cancel.setBackground(new java.awt.Color(255, 153, 0));
        cancel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        jLabel13.setText("Jumlah");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, 23));

        jumlah.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 211, -1));

        alamat.setBackground(new java.awt.Color(255, 255, 153));
        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane2.setViewportView(alamat);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 284, 84));

        treatment.setBackground(new java.awt.Color(255, 255, 204));
        treatment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deep Cleaning", "Quick Cleaning", "Lather Care", "Unyellowing", "Repaint", "Recolour" }));
        jPanel1.add(treatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 284, -1));

        tgl_msk.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.add(tgl_msk, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 211, -1));

        tgl_ambil.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.add(tgl_ambil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 211, -1));

        laki.setBackground(new java.awt.Color(255, 153, 51));
        laki.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        laki.setText("Laki");
        laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiActionPerformed(evt);
            }
        });
        jPanel1.add(laki, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        per.setBackground(new java.awt.Color(255, 153, 51));
        per.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        per.setText("Perempuan");
        per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perActionPerformed(evt);
            }
        });
        jPanel1.add(per, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        jLabel4.setText("Nama");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 52, 23));

        nik.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.add(nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 284, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM TREATMENT ");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shoescare/back2.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel9)
                .addGap(252, 252, 252)
                .addComponent(jLabel1)
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 1000, -1));

        tabel_data.setBackground(new java.awt.Color(204, 204, 204));
        tabel_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_data.setGridColor(new java.awt.Color(0, 0, 0));
        tabel_data.setSelectionBackground(new java.awt.Color(0, 204, 204));
        tabel_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_dataMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabel_data);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 140, 480, 400));

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 550, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
           try{
            String ni = nik.getText();
            String sql = "Delete from data_p where NIK= '"+ni+"'";
            java.sql.PreparedStatement pstm = koneksi.con.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"delete data has been successful");
            tampil();
            kosongkan_form();
           }catch(Exception e){
               JOptionPane.showMessageDialog(null,"error : "+e.getMessage());
           
           }
               
    }//GEN-LAST:event_deleteActionPerformed

    private void lakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiActionPerformed
        if(laki.isSelected()){
            per.setSelected(false);
            gender = "L";
        }
    }//GEN-LAST:event_lakiActionPerformed

    private void perActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perActionPerformed
        if(per.isSelected()){
            laki.setSelected(false);
            gender = "P";
        }// TODO add your handling code here:
    }//GEN-LAST:event_perActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
            
            String sql = "insert into data_p (NIK,nama,gender,noHp,alamat,treatment,jumlah,tgl_masuk,tgl_ambil) values(?,?,?,?,?,?,?,?,?)";
            try {
                PreparedStatement pst = koneksi.con.prepareStatement(sql);
                pst.setString(1, nik.getText());
                pst.setString(2, nama.getText());
                pst.setString(3, gender);
                pst.setString(4, noHp.getText());
                pst.setString(5, alamat.getText());
                pst.setString(6, (String) treatment.getSelectedItem());
                pst.setString(7, jumlah.getText());
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(tgl_msk.getDate());
                pst.setString(8, date);
                SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-MM-dd");
                String date2 = sdf2.format(tgl_ambil.getDate());
                pst.setString(9, date2);
                pst.execute();
                JOptionPane.showMessageDialog(null,"added data has been successful");
                tampil();
                kosongkan_form();
                
                
            } catch (SQLException ex) {
                Logger.getLogger(Data_Pelanggan.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_addActionPerformed

    private void tabel_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_dataMouseClicked
        int baris = tabel_data.rowAtPoint(evt.getPoint());
        String ni = tabel_data.getValueAt(baris,1).toString();
        nik.setText(ni);
        String n = tabel_data.getValueAt(baris,2).toString();
        nama.setText(n);
        String g = tabel_data.getValueAt(baris,3).toString();
        if(g.equals("L")){
            laki.setSelected(true);
            per.setSelected(false);
        }
        else if(g.equals("P")){
            per.setSelected(true);
            laki.setSelected(false);
        }
        String no = tabel_data.getValueAt(baris,4).toString();
        noHp.setText(no);
        String a = tabel_data.getValueAt(baris,5).toString();
        alamat.setText(a);
        String t = tabel_data.getValueAt(baris,6).toString();
        treatment.setSelectedItem(t);
        String j = tabel_data.getValueAt(baris,7).toString();
        jumlah.setText(j);
        

            try {
                DefaultTableModel model = (DefaultTableModel)tabel_data.getModel();
                int s = tabel_data.getSelectedRow();
                Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(s, 8).toString());
                tgl_msk.setDate(date);
                Date date2 = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(s, 9).toString());
                tgl_ambil.setDate(date2);                
            } catch (ParseException ex) {
                Logger.getLogger(Data_Pelanggan.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_tabel_dataMouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
               try{
               String ni = nik.getText();
               String n = nama.getText();
               String no = noHp.getText();
               String a = alamat.getText();
               String t = (String) treatment.getSelectedItem();
               String j = jumlah.getText();
               if(laki.isSelected()){
                   gender = "L";
                   per.setSelected(false);
                   
               }
               else if(per.isSelected()){
                   gender = "P";
                   laki.setSelected(false);
               }
               SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
               String date = sdf.format(tgl_msk.getDate());
               SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-MM-dd");
               String date2 = sdf.format(tgl_ambil.getDate());
               
               String sql = "update data_p set nama= '"+n+"', gender= '"+gender+"',noHp= '"+no+"',alamat = '"+a+"',treatment = '"+t+"',jumlah = '"+j+"',tgl_masuk = '"+date+"',tgl_ambil = '"+date2+"' WHERE nik= '"+ni+"'";
               java.sql.PreparedStatement pstm = koneksi.con.prepareStatement(sql);
               pstm.execute();
               JOptionPane.showMessageDialog(null,"Edit data has been successful");
               tampil();
               kosongkan_form();   
           }catch(Exception e){
               JOptionPane.showMessageDialog(null,"error : "+e.getMessage());
           }
    }//GEN-LAST:event_editActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        kosongkan_form();        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        new Login().setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        ImageIcon m = new ImageIcon(getClass().getResource("backblur.png"));
        jLabel9.setIcon(m);          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        ImageIcon m = new ImageIcon(getClass().getResource("back2.png"));
        jLabel9.setIcon(m);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseExited
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    try {
            
    File file = new File("./src/shoescare/laporan_fix.jrxml"); //membentuk objek dari calss file
    JasperDesign jasperDesign = JRXmlLoader.load(file); 
            param.clear();
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, param,Koneksi.getConnection());
            JasperViewer.viewReport(jasperPrint, false);
    } catch (Exception e) {
            e.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_Pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton cancel;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jumlah;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nik;
    private javax.swing.JTextField noHp;
    private javax.swing.JRadioButton per;
    private javax.swing.JTable tabel_data;
    private com.toedter.calendar.JDateChooser tgl_ambil;
    private com.toedter.calendar.JDateChooser tgl_msk;
    private javax.swing.JComboBox<String> treatment;
    // End of variables declaration//GEN-END:variables


}
